sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wXDLuvA3ZH0MGm13ol70hUgS/JF2fa96LnGKa5YcpYucGfoOQvGVN60Q1bzxfJnEMs95AuNWVtYWVz8/CT3GQrDnIiROwbvqIoq3kSZX2eG1Z9msnzh1epf14newY6WSI1kAyK/kqv//DMBfX+2XAXnSjqLNLeopHZlg8MJLfVEM9Rf6dmjqtvNEqMFQR7OoRHDbjUuONj2kQ97VQiHjqzB4C+DaAC5hRsUMQlX17eNW2DqfY7C6sDfLLkXz2R2le6dIcSae8wkex2lLAKci4O+02IPJAoDvZEueHjmya6p8W1oRk4kkMGlGY3KmFNeffQvtVqk6j+s7aKSxjBZ5klAUNmuGMuaKy/WsmZ/jryMSB+CK5QBBM28FFTH76gexs+//q8STE3X2qhvxqLsPac8qw08oJM93yyyNkIk54u0cgihVewkkinqdL6KD06nL01QpArJ0dnpK1w13bVESBMMMTs28Dg/EiGJ5PK8IlN8wGt+lZSkSue4QZfQVbEdHJYXytptKtXWXmeMKBob/QhaQVR4UoZrMqg40ZsPH7Qp4wPG0ZKHEkf/p9eLX7g/3G7NYt0J/7jw50GYSRQ7BMKnlBpL3vfZtfhutPJi1PimWWjgQpvHGO/PerqYUJN+mSeqwgHB/gvGeREzFOJ+DbOrZ1wJcRmnnF91M76BGPvk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Oh-Money--Money--A-Novel_5962
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy